name: GLaDOS-Signin

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *

jobs:
  GLaDOS-Signin:
    runs-on: ubuntu-latest
    env:
      USE_SMTP: ${{ secrets.USE_SMTP }}
      COOKIE: ${{ secrets.COOKIE }}
      Random: ${{ secrets.Random }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set script permissions
        run: chmod +x signin.sh
      
      - name: signin
        run: |
          OUTPUT=$(./signin.sh)
          echo $OUTPUT
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
